/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prj_login;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class frmCADASTRO extends javax.swing.JFrame {

    /**
     * Creates new form frmCADASTRO
     */
    DAO_bda banco;
    private DefaultListModel modelo;
    
    public frmCADASTRO() {
        initComponents();
        banco = new DAO_bda();
        banco.conexao();
       iniciarDados();
        
    }
    
    public void iniciarDados()
    {
        limparCampos();
        
      //   this.txtAResultadoPesquisa.setText(
      //  banco.getDados() );
        
         this.modelo = banco.getDadosModel();
         this.lstLista.setModel(modelo);
         
        this.txtID.setText(  (banco.getUltimoid()+1) +"" );
    }
    
    public void limparCampos(){
        this.txtID.setText("");
        this.txtNome.setText("");
        this.txtSenha.setText("");
       
    }
    
    public void habilitar(boolean habilitaraux)
    {
        this.txtNome.setEditable(habilitaraux);
        this.txtSenha.setEditable(habilitaraux);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPesID = new javax.swing.JMenuItem();
        mnuPesNome = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        lblSenha.setText("Senha:");

        txtNome.setEditable(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtSenha.setEditable(false);

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblID.setText("ID:");

        txtID.setEditable(false);

        lstLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstListaMouseClicked(evt);
            }
        });
        lstLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstLista);

        jMenu1.setText("Pesquisar");

        mnuPesID.setText("ID");
        mnuPesID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesIDActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPesID);

        mnuPesNome.setText("Nome");
        mnuPesNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPesNomeActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPesNome);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSenha)
                        .addGap(22, 22, 22)
                        .addComponent(txtSenha)
                        .addGap(185, 185, 185))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNome)
                            .addComponent(lblID))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(179, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean gravar=false;
    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
       
        
        if(gravar==false)
        {   this.habilitar(true);
            this.btnInserir.setLabel("Gravar/Cancelar");
            
            this.limparCampos();
            this.txtID.setText( (banco.getUltimoid()+1) +"" );
            gravar=true;
            return;
        }
        if(gravar==true)
        {
            // 0 - 1- 2
            if(  JOptionPane.showConfirmDialog(null,"Deseja Gravar") !=0)
            {
                    gravar=false;
                    habilitar(false);
                    this.btnInserir.setLabel("Inserir");
                    return;
                
            }
        }
        
        String id,nome, senha;
        
        id = this.txtID.getText();
        nome = this.txtNome.getText();
        senha = this.txtSenha.getText();
        
        banco.inserir(id, nome, senha);
        
        iniciarDados();
        
        gravar=false;
        habilitar(false);
        this.btnInserir.setLabel("Inserir");
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        
            // 0 - 1- 2
            if(  JOptionPane.showConfirmDialog(null,"Deseja Excluir") !=0)
            {
                          return;
                
            }
        
        String idexcluir=
                this.txtID.getText();
        banco.excluir(idexcluir);
        this.iniciarDados();
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
         if(gravar==false)
        {   this.habilitar(true);
            this.btnEditar.setLabel("Gravar/Cancelar");
            gravar=true;
            return;
        }
         
         
           if(gravar==true)
        {
            // 0 - 1- 2
            if(  JOptionPane.showConfirmDialog(null,"Deseja Gravar") !=0)
            {
                    gravar=false;
                    habilitar(false);
                    this.btnEditar.setLabel("Editar");
                    return;
                
            }
        }
          String id,nome, senha;
        id = this.txtID.getText();
        nome = this.txtNome.getText();
        senha = this.txtSenha.getText();
        
        banco.editar(id, nome, senha);
        
        iniciarDados();
        
        
        gravar=false;
        habilitar(false);
        this.btnEditar.setLabel("Editar");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void lstListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaValueChanged
        // TODO add your handling code here:
        lstListaMouseClicked(null);
       // System.out.println("TESTE");
    }//GEN-LAST:event_lstListaValueChanged

    private void lstListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstListaMouseClicked
        // TODO add your handling code here:
        try{
        String valorlinha =  this.lstLista.getSelectedValue();
        
        String id, nome, senha;
       
        //ID:1 -  Nom e  :  root      -    Senha:12345
        //0123456 789 10 11 12131415  1617 ...
        id = valorlinha.substring(
                valorlinha.indexOf(":")+1,
                valorlinha.indexOf("-"));
        
        nome = valorlinha.substring(
                valorlinha.indexOf("Nome:")+5,
                valorlinha.indexOf(" - Senha"));
        
        senha = valorlinha.substring(
                valorlinha.indexOf("Senha:")+6,
                valorlinha.length());
                
        
        this.txtID.setText(id+"");
        this.txtNome.setText(nome);
        this.txtSenha.setText(senha);
        
       // System.out.println(valorlinha);
       // System.out.println("ID:"+id);
      //  System.out.println("Nome:"+nome);
      //  System.out.println("Senha:"+senha);
      
      
        
        
        }catch(Exception e){
            System.out.println("Erro:"+e);
        }
    }//GEN-LAST:event_lstListaMouseClicked

    private void mnuPesNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesNomeActionPerformed
        // TODO add your handling code here:
        pesquisar("Nome");
    }//GEN-LAST:event_mnuPesNomeActionPerformed

    private void mnuPesIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPesIDActionPerformed
        // TODO add your handling code here:
        pesquisar("ID");
    }//GEN-LAST:event_mnuPesIDActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void pesquisar(String campo)
    {
        String pesquisa = 
         JOptionPane.showInputDialog("Digite o campo:"+campo);
        
        
          String valorlinha =  banco.pesquisa(pesquisa, campo);
          
          if(valorlinha.equals(""))
          {
              JOptionPane.showMessageDialog(null,"Dado não encontrado");
              return;
          }
        
        String id, nome, senha;
       
        //ID:1 -  Nom e  :  root      -    Senha:12345
        //0123456 789 10 11 12131415  1617 ...
        id = valorlinha.substring(
                valorlinha.indexOf(":")+1,
                valorlinha.indexOf("-"));
        
        nome = valorlinha.substring(
                valorlinha.indexOf("Nome:")+5,
                valorlinha.indexOf(" - Senha"));
        
        senha = valorlinha.substring(
                valorlinha.indexOf("Senha:")+6,
                valorlinha.length());
                
        
        this.txtID.setText(id+"");
        this.txtNome.setText(nome);
        this.txtSenha.setText(senha);
             
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCADASTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JList<String> lstLista;
    private javax.swing.JMenuItem mnuPesID;
    private javax.swing.JMenuItem mnuPesNome;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
